#!/bin/sh
#
# chkconfig: 2345 80 30
# description: Alfresco Content Services
#

RETVAL=0

USER_NAME=alfresco
WHOAMI=`id | awk -F'(' '{print $2}' | awk -F')' '{print $1}'`

if [ "$WHOAMI" != "$USER_NAME" ]
then
        su - $USER_NAME -c "/etc/init.d/alfresco $*"
        exit $?
fi

start () {
    /opt/alfresco/alfresco.sh start "$2"
    RETVAL=$?
    if [ -d "/var/lock/subsys" ] && [ $RETVAL -eq 0 ] ; then
        sudo touch /var/lock/subsys/alfresco
    fi

}

stop () {
    /opt/alfresco/alfresco.sh stop "$2"
    RETVAL=$?
    sudo rm -f /var/lock/subsys/alfresco
}


case "$1" in
    start)
        start "$@"
        ;;
    stop)
        stop "$@"
        ;;
    restart)
        stop "$@"
        start "$@"
        ;;
    *)
        /opt/alfresco/alfresco.sh "$@"
        RETVAL=$?
esac
exit $RETVAL
