#!/bin/bash
# recomemmended sequence
# to note that the only real hard dependency is ActiveMQ
# the other services are pratically essential for almost
# every customer but not hard dependencies:
# Alfresco could work without, it'll limited but it'll work
systemctl start activemq
  systemctl start alfresco-shared-file
    systemctl start alfresco-transform-core
      systemctl start alfresco-transform-router
        systemctl start alfresco
          systemctl start solr


# the shutdown sequence is clearly the opposite of the startup one:
systemctl stop solr
  systemctl stop alfresco
    systemctl stop alfresco-transform-router
      systemctl stop alfresco-transform-core
        systemctl stop alfresco-shared-file
          systemctl stop activemq
